permalink: /:categories/:title.html
url: "http://breakawaysocialcenter.org"
full_name: "Breakaway"
first_name: "Breakaway"
last_name: ""
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Breakaway_chi"
github: "pasindud"
facebook: "mepasindu"
linkined_url: ""
future: true
